version: 2
jobs:
  test:
    working_directory: ~/react-native-ble-test
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      
      - run: yarn lint
      - run: yarn test
workflows:
  version: 2
  lint-test:
    jobs:
      - test
